[package]
name = "rust-host"
version = "0.1.0"
authors = ["miikko <miikka.oksanen@pp1.inet.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.27.0"